import type { LLMClient } from "./client";
import type {
  SessionPlanInput,
  SessionPlan,
  SessionSummaryInput,
  SessionSummary,
  ChatInput,
  ChatTurn,
  CompressInput,
  CompressedSummary,
  ChatMessage,
  MemoryChange,
} from "./types";
import type { AIPlanner, AIChat, AIMemoryManager } from "./interfaces";

function safeJsonParse<T>(raw: string): T | null {
  try {
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

export class DefaultAIPlanner implements AIPlanner {
  constructor(private client: LLMClient) {}

  async proposeSessionPlan(input: SessionPlanInput): Promise<SessionPlan> {
    const systemPrompt =
      "You are a simple workout planner. Respond with JSON only: { title, description?, exercises: [{ exerciseId, sets: [{ targetReps, targetWeight?, targetRpe?, notes? }] }], rationale? }.";

    const userSummary = {
      goal: input.goal,
      recentSessionCount: input.recentSessions.length,
    };

    const response = await this.client.chat({
      systemPrompt,
      messages: [
        {
          role: "user",
          content: `Plan a session for: ${JSON.stringify(userSummary)}`,
        },
      ],
    });

    const parsed = safeJsonParse<SessionPlan>(response.content);

    if (parsed) {
      return {
        title: parsed.title ?? "Autogenerated session",
        description: parsed.description,
        exercises: parsed.exercises ?? [],
        rationale: parsed.rationale ?? "Generated by AI planner.",
      };
    }

    return {
      title: "Autogenerated session",
      description: "Fallback plan due to parsing error.",
      exercises: [],
      rationale: "Fallback plan.",
    };
  }

  async adjustSession(
    input: SessionPlanInput & { request: string },
  ): Promise<SessionPlan> {
    const systemPrompt =
      "You adjust existing workout plans. Respond with JSON only: { title, description?, exercises, rationale? }.";

    const userSummary = {
      goal: input.goal,
      request: input.request,
      currentSessionId: input.currentSessionId,
    };

    const response = await this.client.chat({
      systemPrompt,
      messages: [
        {
          role: "user",
          content: `Adjust this session: ${JSON.stringify(userSummary)}`,
        },
      ],
    });

    const parsed = safeJsonParse<SessionPlan>(response.content);

    if (parsed) {
      return {
        title: parsed.title ?? "Adjusted session",
        description: parsed.description,
        exercises: parsed.exercises ?? [],
        rationale: parsed.rationale ?? "Adjusted by AI planner.",
      };
    }

    return {
      title: "Adjusted session",
      description: "Fallback adjusted plan due to parsing error.",
      exercises: [],
      rationale: "Fallback adjusted plan.",
    };
  }

  async summarizeSession(
    input: SessionSummaryInput,
  ): Promise<SessionSummary> {
    const systemPrompt =
      "You summarize workouts. Respond with JSON only: { headline, positives: string[], risks: string[], advice: string[] }.";

    const summaryInput = {
      sessionId: input.sessionId,
      memoryCount: input.memories.length,
    };

    const response = await this.client.chat({
      systemPrompt,
      messages: [
        {
          role: "user",
          content: `Summarize this session: ${JSON.stringify(summaryInput)}`,
        },
      ],
    });

    const parsed = safeJsonParse<SessionSummary>(response.content);

    if (parsed) {
      return {
        headline: parsed.headline ?? "Session summary",
        positives: parsed.positives ?? [],
        risks: parsed.risks ?? [],
        advice: parsed.advice ?? [],
      };
    }

    return {
      headline: "Session summary",
      positives: [],
      risks: [],
      advice: [],
    };
  }
}

export class DefaultAIChat implements AIChat {
  constructor(private client: LLMClient) {}

  async reply(input: ChatInput): Promise<ChatTurn> {
    const systemPrompt =
      "You are an AI gym coach chatting with the user. Be concise and practical.";

    const response = await this.client.chat({
      systemPrompt,
      messages: input.messages.map((m) => ({
        role: m.role,
        content: m.content,
      })),
    });

    const reply: ChatMessage = {
      role: "assistant",
      content: response.content,
      sessionId: input.sessionId ?? undefined,
    };

    const result: ChatTurn = {
      reply,
      memoryChanges: [],
    };

    return result;
  }

  async compressHistory(input: CompressInput): Promise<CompressedSummary> {
    const systemPrompt =
      "Summarize this conversation briefly for future context. Respond with plain text only.";

    const joined = input.messages
      .map((m) => `${m.role}: ${m.content}`)
      .join("\n");

    const response = await this.client.chat({
      systemPrompt,
      messages: [
        {
          role: "user",
          content: joined,
        },
      ],
    });

    const summary: CompressedSummary = { summary: response.content };
    return summary;
  }
}

export class DefaultAIMemoryManager implements AIMemoryManager {
  // We accept the client so we can implement real extraction later.
  constructor(private _client: LLMClient) {}

  async extractMemories(): Promise<MemoryChange[]> {
    // TODO: implement real memory extraction from chat in a later iteration.
    return [];
  }
}
